name:                hyperpipe
version:             0.0.0

dependencies:
- base >= 4.7 && < 5
- cereal
- bytestring
- HsYAML
- containers
- text
- mtl
- pcap
- unagi-chan
- time
- dbus

library:
  source-dirs: src

executables:
  hyperpipe-daemon:
    main:                Main.hs
    source-dirs:         hyperpipe-daemon
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -fprof-auto
    - -with-rtsopts=-N1
    dependencies:
    - hyperpipe
    - optparse-applicative

  hypertop:
    main:		Main.hs
    source-dirs:	hypertop
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -fprof-auto
    - -with-rtsopts=-N1
    dependencies:
    - brick

tests:
  hyperpipe-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyperpipe
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - string-interpolate
