name:                hyperpipe

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- HsYAML
- containers
- text
- mtl
- pcap
- unagi-chan

library:
  source-dirs: src

executables:
  hyperpipe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyperpipe
    - optparse-applicative

tests:
  hyperpipe-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyperpipe
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - string-interpolate
